version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MixIT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - mixit-network

  spring-boot-app:
    build:
      context: ./MixITServer
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/MixIT
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - mixit-network

  angular-app:
    build:
      context: ./MixITApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mixit-network

networks:
  mixit-network:
    driver: bridge  