version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tasteitroot
      MONGO_INITDB_ROOT_PASSWORD: tasteitserver10
      MONGO_INITDB_DATABASE: tasteit_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: