version: '3.8'

services:
  tasteit-db:
    image: mongo:latest
    container_name: tasteit-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - tasteit-network

  tasteit-api:
    build: 
      context: ./TasteITServer
      dockerfile: Dockerfile
    container_name: tasteit-api
    ports:
      - "8080:8080"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      TASTEIT_SECRET_PHRASE: ${TASTEIT_SECRET_PHRASE}
    depends_on:
      - tasteit-db
    networks:
      - tasteit-network

networks:
  tasteit-network:
    driver: bridge

volumes:
  mongo-data: