version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mixIT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    networks:
      - spring-boot-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mixIT
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge